server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
    session:
      timeout: 30

spring:
  mustache:
    expose-session-attributes: true
  datasource:
      url: jdbc:mariadb://database-2.ciuh4iy8zmzd.ap-northeast-2.rds.amazonaws.com/greendb
      driver-class-name: org.mariadb.jdbc.Driver
      username: root
      password: root1234
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      "[hibernate.format_sql]": true
  

